export const SCHEDULER_CONST = {
	ADD_COLUMN: 'ADD_COLUMN',
	REMOVE_COLUMN: 'REMOVE_COLUMN',
	UPDATE_COLUMN: 'UPDATE_COLUMN',
	ADD_TASK: 'ADD_TASK',
	REMOVE_TASK: 'REMOVE_TASK',
	UPDATE_TASK: 'UPDATE_TASK',
	UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
	REORDER_TASK: 'REORDER_TASK'
}